// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKV9YlmqXyhRf3uGivTMpN9qBx1m0LaHo',
    appId: '1:714943084183:web:6b2e9181293a40b0961bd2',
    messagingSenderId: '714943084183',
    projectId: 'flash-app-64c41',
    authDomain: 'flash-app-64c41.firebaseapp.com',
    storageBucket: 'flash-app-64c41.appspot.com',
    measurementId: 'G-JHBE5E6FFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTM1LZnh0n1pbXwzbqgozn8kdJ2RINS8',
    appId: '1:714943084183:android:f7c456c6bbfbbbc7961bd2',
    messagingSenderId: '714943084183',
    projectId: 'flash-app-64c41',
    storageBucket: 'flash-app-64c41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQ2c7ubyU39f3ugADa9IWB34XkbC3XSc',
    appId: '1:714943084183:ios:80ec7bc122943f7d961bd2',
    messagingSenderId: '714943084183',
    projectId: 'flash-app-64c41',
    storageBucket: 'flash-app-64c41.appspot.com',
    iosClientId: '714943084183-nceoqklvt2ee1ferlf54al2673blp7hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
